const data ={
    products :[
    {
        _id:'1',
        name:'Maison de luxe',
        category: '',
        image:'./image/1.png',
        prix :52000000,
        countInStock: 1,
        info:4.5,
        numReviews :10,
        description:'trop cool',
    },
    {
        _id:'2',
        name:'Maison de classe',
        category: '',
        image:'./image/2.png',
        prix :12800000,
        countInStock: 1,
        info:4.5,
        numReviews :10,
        description:'trop cool',
    },
    {
        _id:'3',
        name:'Maison  luxe',
        category: '',
        image:'./image/3.png',
        prix :78400000,
        countInStock: 1,
        info:4.5,
        numReviews :10,
        description:'trop cool',
    },
    {
        _id:'4',
        name:'Maison top luxe',
        category: '',
        image:'./image/4.png',
        prix :96400000,
        countInStock: 0,
        info: 4.5,
        numReviews :10,
        description:'trop cool',
    },
    {
        _id:'5',
        name:'Maison a la prairi',
        category: '',
        image:'./image/5.png',
        prix :345800000,
        countInStock: 1 ,
        info:4.5,
        numReviews :10,
        description:'trop cool',
    },
    {
        _id:'6',
        name:'Maison en bois',
        category: '',
        image:'./image/6.png',
        prix :486800000,
        countInStock: 0,
        info:4.5,
        numReviews :10 ,
        description:'trop cool',
    },
],
};
export default data ;