const data ={
    products :[
        {
            _id:'1',
            name:'Maison de luxe',
            category: '',
            image:'./image/1.jpg',
            prix :52000000,
            countInStock: 20,
            info: 4.5,
            numReviews :10,
            description:'trop cool',
        },
        {
            _id:'2',
            name:'Maison de classe',
            category: '',
            image:'./image/2.jpg',
            prix :12800000,
            countInStock: 20,
            info: 4.5,
            numReviews :10,
            description:'trop cool',
        },
        {
            _id:'3',
            name:'Maison  luxe',
            category: '',
            image:'./image/3.jpg',
            prix :78400000,
            countInStock: 20,
            info: 4,
            numReviews :10,
            description:'trop cool',
        },
        {
            _id:'4',
            name:'Maison top luxe',
            category: '',
            image:'./image/4.jpg',
            prix :96400000,
            countInStock: 20,
            info: 4,
            numReviews :10,
            description:'trop cool',
        },
        {
            _id:'5',
            name:'Maison a la prairi',
            category: '',
            image:'./image/5.jpg',
            prix :345800000,
            countInStock: 10,
            info: 4.5,
            numReviews :10,
            description:'trop cool',
        },
        {
            _id:'6',
            name:'Maison en bois',
            category: '',
            image:'./image/6.jpg',
            prix :486800000,
            countInStock: 20,
            info: 4.5,
            numReviews :10 ,
            description:'trop cool',
        },
    ],
    };
export default data ;