const data ={
    products :[
    {
        _id:'1',
        name:'Maison de luxe',
        category: '',
        image:'./image/1.png',
        prix :12800000,
        info:4.5,
        numReview :10,
        description:'trop cool',
    },
    {
        _id:'2',
        name:'Maison de luxe',
        category: '',
        image:'./image/1.png',
        prix :12800000,
        info:4.5,
        numReview :10,
        description:'trop cool',
    },
    {
        _id:'3',
        name:'Maison de luxe',
        category: '',
        image:'./image/2.png',
        prix :12800000,
        info:4.5,
        numReview :10,
        description:'trop cool',
    },
    {
        _id:'4',
        name:'Maison de luxe',
        category: '',
        image:'./image/2.png',
        prix :12800000,
        info: 4.5,
        numReview :10,
        description:'trop cool',
    },
    {
        _id:'5',
        name:'Maison de luxe',
        category: '',
        image:'./image/1.png',
        prix :12800000,
        info:4.5,
        numReview :10,
        description:'trop cool',
    },
    {
        _id:'6',
        name:'Maison de luxe',
        category: '',
        image:'./image/2.png',
        prix :12800000,
        info:4.5,
        numReview :10,
        description:'trop cool',
    },
    {
        _id:'7',
        name:'Maison de luxe',
        category: '',
        image:'./image/1.png',
        prix :12800000,
        info:4.5,
        numReview :10,
        description:'trop cool',
    },
    {
        _id:'8',
        name:'Maison de luxe',
        category: '',
        image:'./image/2.png',
        prix :12800000,
        info:4.5,
        numReview :10, 
        description:'trop cool',
    },
],
};
export default data ;